"use client";

import { ArrowRight, Car, Eye, EyeOff, LockKeyhole, Mail, UserRound } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { authApi, saveSession } from "@/lib/api";

export function AuthForm() {
  const router = useRouter(); const [mode, setMode] = useState<"login" | "register">("login"); const [showPassword, setShowPassword] = useState(false); const [form, setForm] = useState({ name: "", email: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setLoading(true); try { const session = mode === "login" ? await authApi.login({ email: form.email, password: form.password }) : await authApi.register(form); saveSession(session); router.replace("/"); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo iniciar sesión"); } finally { setLoading(false); } }
  return <div className="auth-form"><div className="mobile-auth-brand"><span className="brand-mark"><Car size={20} /></span>CarNote</div><p className="eyebrow">{mode === "login" ? "BIENVENIDO DE VUELTA" : "EMPIEZA HOY"}</p><h2>{mode === "login" ? "Entra a tu espacio" : "Crea tu cuenta"}</h2><p className="auth-subtitle">{mode === "login" ? "Continúa donde lo dejaste." : "Tu flota, organizada desde un solo lugar."}</p><button className="google-button" type="button" onClick={() => setError("Configura las credenciales de Google para activar este acceso.")}><span className="google-g">G</span> Continuar con Google</button><div className="or-divider"><span>o continúa con email</span></div><form onSubmit={submit}>{mode === "register" && <label><span>Nombre completo</span><div className="input-wrap"><UserRound size={16} /><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Alex Morgan" required /></div></label>}<label><span>Email</span><div className="input-wrap"><Mail size={16} /><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="tu@email.com" required /></div></label><label><span>Contraseña</span><div className="input-wrap"><LockKeyhole size={16} /><input type={showPassword ? "text" : "password"} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="••••••••" minLength={6} required /><button type="button" className="password-toggle" onClick={() => setShowPassword(!showPassword)} aria-label="Mostrar contraseña">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>{mode === "login" && <div className="form-options"><label className="remember"><input type="checkbox" /> Recordarme</label><button type="button" className="link-button">¿Olvidaste tu contraseña?</button></div>}{error && <p className="error-message">{error}</p>}<button className="auth-submit" type="submit" disabled={loading}>{loading ? "Conectando..." : mode === "login" ? "Iniciar sesión" : "Crear cuenta"}<ArrowRight size={16} /></button></form><p className="switch-auth">{mode === "login" ? "¿Aún no tienes cuenta?" : "¿Ya tienes una cuenta?"} <button className="link-button" onClick={() => { setError(""); setMode(mode === "login" ? "register" : "login"); }}>{mode === "login" ? "Regístrate gratis" : "Inicia sesión"}</button></p><small className="terms">Al continuar, aceptas nuestros términos de uso y política de privacidad.</small></div>;
}
